[build]
  publish = "dist/cms/browser"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "22.12"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200